spring.application.name=app

spring.datasource.url=jdbc:postgressql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=MaL8033038

# Драйвер
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=create

# SQL команды в консоли для отладки
spring.jpa.show-sql=true